### ISSUE TITLE
Should the src layout of the swapchain image be VK_IMAGE_LAYOUT_UNDEFINED in the layout transition before blit?

### ISSUE THREAD

**Issue by yukli-amd** [kleinerm/jesse-cube#2]
Hi @keith-packard,

I noticed that you set the src layout of the swapchain image to VK_IMAGE_LAYOUT_PRESENT_SRC_KHR:
https://github.com/kleinerm/jesse-cube/blob/1a949a325e6a7c5fa1097955ba745e01771cb638/cube.c#L822
But it seems that this image has not been touched before if `use_blit` is set, is it make more sense to the set src layout to `VK_IMAGE_LAYOUT_UNDEFINED`?

**Comment by kleinerm** [comment]
Hi @yukli-amd I think you targeted the wrong respository with your question? This is just my own throwaway repo, which was used for prototyping some stuff, but is essentially unused since a long time. You should look at keithp's own Github. Or maybe the official Khronos GitHub has a similar repo? Closing for now.
